# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       graphviz

# >> macros
# << macros
%define pluginsver 6

Summary:    Greph visualization
Version:    8.1.0
Release:    0
Group:      Applications
License:    EPL-1.0
URL:        https://www.graphviz.org/
Source0:    %{name}-%{version}.tar.xz
Source100:  graphviz.yaml
Source101:  graphviz-rpmlintrc
Requires:   %{name}-plugins-core = %{version}-%{release}
BuildRequires:  pkgconfig(zlib)
BuildRequires:  pkgconfig(poppler)
BuildRequires:  pkgconfig(libpng)
BuildRequires:  pkgconfig(lua)
BuildRequires:  pkgconfig(freetype2)
BuildRequires:  pkgconfig(pango)
BuildRequires:  pkgconfig(pangocairo)
BuildRequires:  python3-rpm-macros
BuildRequires:  python3-devel
BuildRequires:  gmp-devel
BuildRequires:  librsvg-devel
BuildRequires:  libwebp-devel
BuildRequires:  swig

%description

A collection of tools for the manipulation and layout of graphs (as in
nodes and edges, not as in bar-charts).

%if "%{?vendor}" == "chum"
Title: Graphviz
PackagedBy: nephros
Categories:
 - Library
Custom:
  Repo: https://gitlab.com/graphviz/graphviz
  PackagingRepo: https://github.com/sailfishos-chum/graphviz
PackageIcon: %{url}/master/icons/%{name}.svg
Links:
  Homepage: %{url}
  Help: %{url}/discussions
  Bugtracker: %{url}/issues
  Donation: https://openrepos.net/donate
%endif


%package devel
Summary:    Development Files for %{name}
Group:      Development
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-libs = %{version}-%{release}

%description devel
%{summary}.

%package python
Summary:    Python extension for %{name}
Group:      Applications/Multimedia
Requires:   %{name} = %{version}-%{release}
Requires:   python3-base

%description python
%{summary}.

%package plugins-core
Summary:    Core plugins for %{name}
Group:      Applications/Multimedia
Requires:   %{name} = %{version}-%{release}

%description plugins-core
%{summary}.

%package plugins-misc
Summary:    Misc plugins for %{name}
Group:      Applications/Multimedia
Requires:   %{name} = %{version}-%{release}

%description plugins-misc
%{summary}.

%package libs
Summary:    Libraries for %{name}
Group:      Applications/Multimedia
Requires:   %{name} = %{version}-%{release}
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig

%description libs
%{summary}.

%package graphs
Summary:    Demo graphs for %{name}
Group:      Applications/Multimedia
BuildArch:  noarch
Requires:   %{name} = %{version}-%{release}

%description graphs
Some demo graphs for graphviz.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --enable-ltdl \
    --without-libgd \
    --without-gdk \
    --without-gtk \
    --without-gtkgl \
    --without-gtkglext \
    --without-qt \
    --without-smyrna \
    --without-x \
    --enable-perl \
    --enable-python3 \
    --enable-ruby \
    --disable-d \
    --disable-go \
    --disable-guile \
    --disable-java \
    --disable-javascript \
    --disable-ocaml \
    --disable-php \
    --disable-python \
    --disable-r \
    --disable-sharp \
    --disable-tcl

make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
rm -rf %{buildroot}%{_docdir}
rm -rf %{buildroot}%{_mandir}
# Ghost plugins config
touch %{buildroot}%{_libdir}/graphviz/config%{pluginsver}
# << install post

%pre
# >> pre
rm -rf %{_libdir}/graphviz/config%{pluginsver} || :
# << pre

%post
# >> post
LD_LIBRARY_PATH=%{_libdir} %{_bindir}/dot -c
# << post

%post plugins-core
# >> post plugins-core
[ -x %{_bindir}/dot ] && LD_LIBRARY_PATH=%{_libdir} %{_bindir}/dot -c || :
# << post plugins-core

%postun plugins-core
# >> postun plugins-core
# if there is no dot after everything else is done, then remove config
if [ $1 -eq 0 ]; then
rm -f %{_libdir}/graphviz/config%{pluginsver} || :
fi
# << postun plugins-core

%post plugins-misc
# >> post plugins-misc
LD_LIBRARY_PATH=%{_libdir} %{_bindir}/dot -c || :
# << post plugins-misc

%postun plugins-misc
# >> postun plugins-misc
[ -x %{_bindir}/dot ] && LD_LIBRARY_PATH=%{_libdir} %{_bindir}/dot -c || :
# << postun plugins-misc

%post libs -p /sbin/ldconfig

%postun libs -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
%license COPYING
%{_bindir}/*
%dir %{_datadir}/%{name}
%{_datadir}/%{name}/gvpr
%exclude %{_datadir}/%{name}/demo
%ghost %{_libdir}/graphviz/config%{pluginsver}
%exclude %{python3_sitearch}/*.so
%exclude %{python3_sitearch}/__pycache__
# >> files
# << files

%files devel
%defattr(-,root,root,-)
%{_includedir}/*
%{_libdir}/*.so
%{_prefix}/%{_lib}/pkgconfig/*.pc
# >> files devel
# << files devel

%files python
%defattr(-,root,root,-)
%{python3_sitearch}/*.so
%{python3_sitearch}/*.py
%{_libdir}/%{name}/python3
# >> files python
# << files python

%files plugins-core
%defattr(-,root,root,-)
%dir %{_libdir}/%{name}
%{_libdir}/graphviz/libgvplugin_core.so.*
%{_libdir}/graphviz/libgvplugin_dot_layout.so.*
%{_libdir}/graphviz/libgvplugin_neato_layout.so.*
# >> files plugins-core
# << files plugins-core

%files plugins-misc
%defattr(-,root,root,-)
%dir %{_libdir}/%{name}
%{_libdir}/%{name}/libgvplugin*.so.*
%exclude %{_libdir}/graphviz/libgvplugin_core.so.*
%exclude %{_libdir}/graphviz/libgvplugin_dot_layout.so.*
%exclude %{_libdir}/graphviz/libgvplugin_neato_layout.so.*
# >> files plugins-misc
# << files plugins-misc

%files libs
%defattr(-,root,root,-)
%{_libdir}/libcdt.so.*
%{_libdir}/libcgraph.so.*
%{_libdir}/libgvc.so.*
%{_libdir}/libgvpr.so.*
%{_libdir}/libpathplan.so.*
%{_libdir}/libxdot.so.4*
%{_libdir}/liblab_gamut.so.*
%exclude %{_libdir}/graphviz/*
# >> files libs
# << files libs

%files graphs
%defattr(-,root,root,-)
%dir %{_datadir}/graphviz
%{_datadir}/graphviz/graphs
# >> files graphs
# << files graphs
